baseURL = 'https://kaddish.post-self.ink/'
languageCode = 'en-us'
title = 'Kaddish'
theme = 'maddybook'
paginatePath = ""
disablePathToLower = true

[pagination]
    path = ""

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Rye Progress'
    home = 'https://makyo.ink/'
    copyright = '2024'
    subtitle = 'A Post-Self Story'
    subtitleLink = 'https://post-self.ink'
    customCSS = ['/css/kaddish.css']

[markup.goldmark.renderer]
    unsafe = true
